import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_wallet_model.freezed.dart';
// optional: Since our CreateWalletModel class is serializable, we must add this line.
// But if CreateWalletModel was not serializable, we could skip it.
part 'create_wallet_model.g.dart';

@freezed
abstract class CreateWalletModel with _$CreateWalletModel {
  const factory CreateWalletModel({required String name, required int amount}) =
      _CreateWalletModel;

  factory CreateWalletModel.fromJson(Map<String, Object?> json) =>
      _$CreateWalletModelFromJson(json);
}
