import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'total_wallet_balance_model.freezed.dart';
// optional: Since our TotalWalletBalanceModel class is serializable, we must add this line.
// But if TotalWalletBalanceModel was not serializable, we could skip it.
part 'total_wallet_balance_model.g.dart';

@freezed
abstract class TotalWalletBalanceModel with _$TotalWalletBalanceModel {
  const factory TotalWalletBalanceModel({required int balance}) =
      _TotalWalletBalanceModel;

  factory TotalWalletBalanceModel.fromJson(Map<String, Object?> json) =>
      _$TotalWalletBalanceModelFromJson(json);
}
