import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'update_wallet_model.freezed.dart';
// optional: Since our UpdateWalletModel class is serializable, we must add this line.
// But if UpdateWalletModel was not serializable, we could skip it.
part 'update_wallet_model.g.dart';

@freezed
abstract class UpdateWalletModel with _$UpdateWalletModel {
  const factory UpdateWalletModel({
    required String walletName,
    required int amount,
    required String wallet_id,
  }) = _UpdateWalletModel;

  factory UpdateWalletModel.fromJson(Map<String, Object?> json) =>
      _$UpdateWalletModelFromJson(json);
}
