import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'wallet_names_model.freezed.dart';
// optional: Since our WalletNamesModel class is serializable, we must add this line.
// But if WalletNamesModel was not serializable, we could skip it.
part 'wallet_names_model.g.dart';

@freezed
abstract class WalletNamesModel with _$WalletNamesModel {
  const factory WalletNamesModel({required List<String> wallets}) =
      _WalletNamesModel;

  factory WalletNamesModel.fromJson(Map<String, Object?> json) =>
      _$WalletNamesModelFromJson(json);
}
