import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/wallet/models/wallet_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'wallets_model.freezed.dart';
// optional: Since our WalletsModel class is serializable, we must add this line.
// But if WalletsModel was not serializable, we could skip it.
part 'wallets_model.g.dart';

@freezed
abstract class WalletsModel with _$WalletsModel {
  const factory WalletsModel({List<WalletModel>? wallets}) = _WalletsModel;

  factory WalletsModel.fromJson(Map<String, Object?> json) =>
      _$WalletsModelFromJson(json);
}
