import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'income_model.freezed.dart';
// optional: Since our IncomeModel class is serializable, we must add this line.
// But if IncomeModel was not serializable, we could skip it.
part 'income_model.g.dart';

@freezed
abstract class IncomeModel with _$IncomeModel {
  const factory IncomeModel({required String bankName, required int amount}) =
      _IncomeModel;

  factory IncomeModel.fromJson(Map<String, Object?> json) =>
      _$IncomeModelFromJson(json);
}
