import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/constants/income_source.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'total_income_model.freezed.dart';
// optional: Since our TotalIncomeModel class is serializable, we must add this line.
// But if TotalIncomeModel was not serializable, we could skip it.
part 'total_income_model.g.dart';

@freezed
abstract class TotalIncomeModel with _$TotalIncomeModel {
  const factory TotalIncomeModel({required int income}) = _TotalIncomeModel;

  factory TotalIncomeModel.fromJson(Map<String, Object?> json) =>
      _$TotalIncomeModelFromJson(json);
}
