import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'export_data_user_model.freezed.dart';
// optional: Since our ExportDataUserModel class is serializable, we must add this line.
// But if ExportDataUserModel was not serializable, we could skip it.
part 'export_data_user_model.g.dart';

@freezed
abstract class ExportDataUserModel with _$ExportDataUserModel {
  const factory ExportDataUserModel({
    required String dataType,
    required String dateRange,
    required String format,
  }) = _ExportDataUserModel;

  factory ExportDataUserModel.fromJson(Map<String, dynamic> json) =>
      _$ExportDataUserModelFromJson(json);
}
