import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/users/models/user_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'login_user_response_model.freezed.dart';
// optional: Since our LoginUserResponseModel class is serializable, we must add this line.
// But if LoginUserResponseModel was not serializable, we could skip it.
part 'login_user_response_model.g.dart';

@freezed
abstract class LoginUserResponseModel with _$LoginUserResponseModel {
  const factory LoginUserResponseModel({
    required UserModel user,
    required String token,
  }) = _LoginUserResponseModel;

  factory LoginUserResponseModel.fromJson(Map<String, dynamic> json) =>
      _$LoginUserResponseModelFromJson(json);
}
