import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'login_user_model.freezed.dart';
// optional: Since our LoginUserModel class is serializable, we must add this line.
// But if LoginUserModel was not serializable, we could skip it.
part 'login_user_model.g.dart';

@freezed
abstract class LoginUserModel with _$LoginUserModel {
  const factory LoginUserModel({
    required String email,
    required String password,
  }) = _LoginUserModel;

  factory LoginUserModel.fromJson(Map<String, Object?> json) =>
      _$LoginUserModelFromJson(json);
}
