import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_image_model.freezed.dart';
// optional: Since our UserImageModel class is serializable, we must add this line.
// But if UserImageModel was not serializable, we could skip it.
part 'user_image_model.g.dart';

@freezed
abstract class UserImageModel with _$UserImageModel {
  const factory UserImageModel({String? imgUrl}) = _UserImageModel;

  factory UserImageModel.fromJson(Map<String, dynamic> json) =>
      _$UserImageModelFromJson(json);
}
