import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/budget/models/budget_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'budget_month_model.freezed.dart';
// optional: Since our BudgetMonthModel class is serializable, we must add this line.
// But if BudgetMonthModel was not serializable, we could skip it.
part 'budget_month_model.g.dart';

@freezed
abstract class BudgetMonthModel with _$BudgetMonthModel {
  const factory BudgetMonthModel({required String month}) = _BudgetMonthModel;

  factory BudgetMonthModel.fromJson(Map<String, Object?> json) =>
      _$BudgetMonthModelFromJson(json);
}
