import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/budget/models/budget_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'budgets_model.freezed.dart';
// optional: Since our BudgetsModel class is serializable, we must add this line.
// But if BudgetsModel was not serializable, we could skip it.
part 'budgets_model.g.dart';

@freezed
abstract class BudgetsModel with _$BudgetsModel {
  const factory BudgetsModel({required List<BudgetModel> budgets}) =
      _BudgetsModel;

  factory BudgetsModel.fromJson(Map<String, Object?> json) =>
      _$BudgetsModelFromJson(json);
}
