import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_budget_model.freezed.dart';
// optional: Since our CreateBudgetModel class is serializable, we must add this line.
// But if CreateBudgetModel was not serializable, we could skip it.
part 'create_budget_model.g.dart';

@freezed
abstract class CreateBudgetModel with _$CreateBudgetModel {
  const factory CreateBudgetModel({
    required String name,
    required int totalBudget,
  }) = _CreateBudgetModel;

  factory CreateBudgetModel.fromJson(Map<String, Object?> json) =>
      _$CreateBudgetModelFromJson(json);
}
