import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'delete_budget_model.freezed.dart';
// optional: Since our DeleteBudgetModel class is serializable, we must add this line.
// But if DeleteBudgetModel was not serializable, we could skip it.
part 'delete_budget_model.g.dart';

@freezed
abstract class DeleteBudgetModel with _$DeleteBudgetModel {
  const factory DeleteBudgetModel({required String budgetId}) =
      _DeleteBudgetModel;

  factory DeleteBudgetModel.fromJson(Map<String, Object?> json) =>
      _$DeleteBudgetModelFromJson(json);
}
