import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'update_budget_model.freezed.dart';
// optional: Since our UpdateBudgetModel class is serializable, we must add this line.
// But if UpdateBudgetModel was not serializable, we could skip it.
part 'update_budget_model.g.dart';

@freezed
abstract class UpdateBudgetModel with _$UpdateBudgetModel {
  const factory UpdateBudgetModel({
    required String budgetId,
    required int totalBudget,
    required String name,
    required int current,
  }) = _BudgetModel;

  factory UpdateBudgetModel.fromJson(Map<String, Object?> json) =>
      _$UpdateBudgetModelFromJson(json);
}
