import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/bank/models/bank_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'banks_model.freezed.dart';
// optional: Since our BanksModel class is serializable, we must add this line.
// But if BanksModel was not serializable, we could skip it.
part 'banks_model.g.dart';

@freezed
abstract class BanksModel with _$BanksModel {
  const factory BanksModel({List<BankModel>? banks}) = _BanksModel;

  factory BanksModel.fromJson(Map<String, dynamic> json) =>
      _$BanksModelFromJson(json);
}
