import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'bank_model.freezed.dart';
// optional: Since our BankModel class is serializable, we must add this line.
// But if BankModel was not serializable, we could skip it.
part 'bank_model.g.dart';

@freezed
abstract class BankModel with _$BankModel {
  const factory BankModel({
    required String name,
    required int amount,
    required String userId,
    required String accountNumber,
  }) = _BankModel;

  factory BankModel.fromJson(Map<String, Object?> json) =>
      _$BankModelFromJson(json);
}
