import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_bank_account_model.freezed.dart';
// optional: Since our CreateBankAccountModel class is serializable, we must add this line.
// But if CreateBankAccountModel was not serializable, we could skip it.
part 'create_bank_account_model.g.dart';

@freezed
abstract class CreateBankAccountModel with _$CreateBankAccountModel {
  const factory CreateBankAccountModel({
    required String bankName,
    required int amount,
  }) = _CreateBankAccountModel;

  factory CreateBankAccountModel.fromJson(Map<String, Object?> json) =>
      _$CreateBankAccountModelFromJson(json);
}
