import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'total_bank_balance_model.freezed.dart';
// optional: Since our TotalBankBalanceModel class is serializable, we must add this line.
// But if TotalBankBalanceModel was not serializable, we could skip it.
part 'total_bank_balance_model.g.dart';

@freezed
abstract class TotalBankBalanceModel with _$TotalBankBalanceModel {
  const factory TotalBankBalanceModel({required int balance}) =
      _TotalBankBalanceModel;

  factory TotalBankBalanceModel.fromJson(Map<String, Object?> json) =>
      _$TotalBankBalanceModelFromJson(json);
}
