import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'update_bank_model.freezed.dart';
// optional: Since our UpdateBankModel class is serializable, we must add this line.
// But if UpdateBankModel was not serializable, we could skip it.
part 'update_bank_model.g.dart';

@freezed
abstract class UpdateBankModel with _$UpdateBankModel {
  const factory UpdateBankModel({
    required int amount,
    required String accountNumber,
  }) = _UpdateBankModel;

  factory UpdateBankModel.fromJson(Map<String, Object?> json) =>
      _$UpdateBankModelFromJson(json);
}
