// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Lq23hB65cfPETr8kUi7O0etvhPj62QE',
    appId: '1:727081287744:web:b997b6fd7005ef8c311fa5',
    messagingSenderId: '727081287744',
    projectId: 'montra-6ec57',
    authDomain: 'montra-6ec57.firebaseapp.com',
    storageBucket: 'montra-6ec57.firebasestorage.app',
    measurementId: 'G-6E5M9G8DV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8lpSjSAr0ZVSqDa1CV9sagpvl11eGR_c',
    appId: '1:727081287744:android:ae16828e55f1b97d311fa5',
    messagingSenderId: '727081287744',
    projectId: 'montra-6ec57',
    storageBucket: 'montra-6ec57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1E2i5xGJQdkdXmCa1aeiYOXQ3OzG7hUo',
    appId: '1:727081287744:ios:6e86a4f616bc7620311fa5',
    messagingSenderId: '727081287744',
    projectId: 'montra-6ec57',
    storageBucket: 'montra-6ec57.firebasestorage.app',
    iosBundleId: 'com.example.montra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1E2i5xGJQdkdXmCa1aeiYOXQ3OzG7hUo',
    appId: '1:727081287744:ios:6e86a4f616bc7620311fa5',
    messagingSenderId: '727081287744',
    projectId: 'montra-6ec57',
    storageBucket: 'montra-6ec57.firebasestorage.app',
    iosBundleId: 'com.example.montra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Lq23hB65cfPETr8kUi7O0etvhPj62QE',
    appId: '1:727081287744:web:540efec94fa21a2b311fa5',
    messagingSenderId: '727081287744',
    projectId: 'montra-6ec57',
    authDomain: 'montra-6ec57.firebaseapp.com',
    storageBucket: 'montra-6ec57.firebasestorage.app',
    measurementId: 'G-NPW7C1MQ45',
  );

}