import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/expense/models/expenses_model.dart';
import 'package:montra/logic/api/income/models/incomes_model.dart';
import 'package:montra/logic/api/transfer/models/transfers_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'transactions_model.freezed.dart';
// optional: Since our TransactionsModels class is serializable, we must add this line.
// But if TransactionsModels was not serializable, we could skip it.
part 'transactions_model.g.dart';

@freezed
abstract class TransactionsModels with _$TransactionsModels {
  const factory TransactionsModels({
    required TransfersModel transfer,
    required IncomesModel incomes,
    required ExpensesModel expenses,
  }) = _TransactionsModels;

  factory TransactionsModels.fromJson(Map<String, Object?> json) =>
      _$TransactionsModelsFromJson(json);
}
