import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/constants/expense_type.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'expense_stats_summary_model.freezed.dart';
// optional: Since our ExpenseStatsSummaryModel class is serializable, we must add this line.
// But if ExpenseStatsSummaryModel was not serializable, we could skip it.
part 'expense_stats_summary_model.g.dart';

@freezed
abstract class ExpenseStatsSummaryModel with _$ExpenseStatsSummaryModel {
  const factory ExpenseStatsSummaryModel({
    required int today,
    required int week,
    required int month,
    required int year,
  }) = _ExpenseStatsSummaryModel;

  factory ExpenseStatsSummaryModel.fromJson(Map<String, Object?> json) =>
      _$ExpenseStatsSummaryModelFromJson(json);
}
