import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'expense_model.freezed.dart';
// optional: Since our ExpenseModel class is serializable, we must add this line.
// But if ExpenseModel was not serializable, we could skip it.
part 'expense_model.g.dart';

@freezed
abstract class ExpenseModel with _$ExpenseModel {
  const factory ExpenseModel({required String bankName, required int amount}) =
      _ExpenseModel;

  factory ExpenseModel.fromJson(Map<String, Object?> json) =>
      _$ExpenseModelFromJson(json);
}
