import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/expense/models/expense_frequency_data_set_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'expense_stats_frequency_model.freezed.dart';
// optional: Since our ExpenseStatsFrequencyModel class is serializable, we must add this line.
// But if ExpenseStatsFrequencyModel was not serializable, we could skip it.
part 'expense_stats_frequency_model.g.dart';

@freezed
abstract class ExpenseStatsFrequencyModel with _$ExpenseStatsFrequencyModel {
  const factory ExpenseStatsFrequencyModel({
    required List<ExpenseFrequencyDataSetModel> today,
    required List<ExpenseFrequencyDataSetModel> week,
    required List<ExpenseFrequencyDataSetModel> month,
    required List<ExpenseFrequencyDataSetModel> year,
  }) = _ExpenseStatsFrequencyModel;

  factory ExpenseStatsFrequencyModel.fromJson(Map<String, Object?> json) =>
      _$ExpenseStatsFrequencyModelFromJson(json);
}
