import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/constants/expense_type.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'expense_model.freezed.dart';
// optional: Since our ExpenseModel class is serializable, we must add this line.
// But if ExpenseModel was not serializable, we could skip it.
part 'expense_model.g.dart';

@freezed
abstract class ExpenseModel with _$ExpenseModel {
  const factory ExpenseModel({
    required String name,
    required String userId,
    required String expenseId,
    required int amount,
    required ExpenseType source,
    String? attachment,
    String? description,
    required DateTime createdAt,
  }) = _ExpenseModel;

  factory ExpenseModel.fromJson(Map<String, Object?> json) =>
      _$ExpenseModelFromJson(json);
}
