import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/logic/api/expense/models/expense_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'expenses_model.freezed.dart';
// optional: Since our ExpensesModel class is serializable, we must add this line.
// But if ExpensesModel was not serializable, we could skip it.
part 'expenses_model.g.dart';

@freezed
abstract class ExpensesModel with _$ExpensesModel {
  const factory ExpensesModel({required List<ExpenseModel> expenses}) =
      _ExpensesModel;

  factory ExpensesModel.fromJson(Map<String, Object?> json) =>
      _$ExpensesModelFromJson(json);
}
