import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:montra/constants/income_source.dart';
import 'package:montra/logic/api/expense/models/expense_stats_summary_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'expense_frequency_data_set_model.freezed.dart';
// optional: Since our ExpenseFrequencyDataSetModel class is serializable, we must add this line.
// But if ExpenseFrequencyDataSetModel was not serializable, we could skip it.
part 'expense_frequency_data_set_model.g.dart';

@freezed
abstract class ExpenseFrequencyDataSetModel
    with _$ExpenseFrequencyDataSetModel {
  const factory ExpenseFrequencyDataSetModel({
    required String label,
    required int total,
  }) = _ExpenseFrequencyDataSetModel;

  factory ExpenseFrequencyDataSetModel.fromJson(Map<String, Object?> json) =>
      _$ExpenseFrequencyDataSetModelFromJson(json);
}
