import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'total_expense_model.freezed.dart';
// optional: Since our TotalExpenseModel class is serializable, we must add this line.
// But if TotalExpenseModel was not serializable, we could skip it.
part 'total_expense_model.g.dart';

@freezed
abstract class TotalExpenseModel with _$TotalExpenseModel {
  const factory TotalExpenseModel({required int expense}) = _TotalExpenseModel;

  factory TotalExpenseModel.fromJson(Map<String, Object?> json) =>
      _$TotalExpenseModelFromJson(json);
}
