# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and distribute APK to Firebase App Distribution"
  lane :beta do
    # Step 1: Build the APK using Flutter
    sh("flutter clean")
    sh("flutter build apk --release")
  
    # Step 2: Upload to Firebase App Distribution
    firebase_app_distribution(
      app: "1:727081287744:android:ae16828e55f1b97d311fa5", 
      groups: "internal-testers", 
      release_notes: "New test build 🚀",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
    )
  end
  

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
