import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_transfer_model.freezed.dart';
// optional: Since our CreateTransferModel class is serializable, we must add this line.
// But if CreateTransferModel was not serializable, we could skip it.
part 'create_transfer_model.g.dart';

@freezed
abstract class CreateTransferModel with _$CreateTransferModel {
  const factory CreateTransferModel({
    required int amount,
    required String sender,
    required String receiver,
    required bool isExpense,
  }) = _CreateTransferModel;

  factory CreateTransferModel.fromJson(Map<String, Object?> json) =>
      _$CreateTransferModelFromJson(json);
}
