import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'transfer_model.freezed.dart';
// optional: Since our TransferModel class is serializable, we must add this line.
// But if TransferModel was not serializable, we could skip it.
part 'transfer_model.g.dart';

@freezed
abstract class TransferModel with _$TransferModel {
  const factory TransferModel({
    required int amount,
    required String sender,
    required String receiver,
    required String userId,
    required String transferId,
    required bool isExpense,
    required DateTime createdAt,
  }) = _TransferModel;

  factory TransferModel.fromJson(Map<String, Object?> json) =>
      _$TransferModelFromJson(json);
}
